### ISSUE TITLE
The release version is buggy

### ISSUE THREAD

**Issue by dainiusjocas** [quarkiverse/quarkus-lucene#125]
Even if the version file is set

```yaml
name: Quarkiverse Extension
release:
  current-version: 2.0
  next-version: 2.1-SNAPSHOT
```

the version released is just "2" :) 

https://central.sonatype.com/artifact/io.quarkiverse.lucene/quarkus-lucene/2
